
import { AITool, BlogPost, Category, SiteSettings } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Productivity', slug: 'productivity', icon: '⚡', count: 151 },
  { id: '2', name: 'Design & Art', slug: 'design-art', icon: '🎨', count: 98 },
  { id: '3', name: 'Video & Motion', slug: 'video-motion', icon: '🎬', count: 75 },
  { id: '4', name: 'Coding & Dev', slug: 'coding-dev', icon: '💻', count: 64 },
  { id: '5', name: 'Marketing & Ads', slug: 'marketing-ads', icon: '📈', count: 52 },
  { id: '6', name: 'Social Media', slug: 'social-media', icon: '📱', count: 42 },
  { id: '7', name: 'Automation', slug: 'automation', icon: '🤖', count: 38 },
  { id: '8', name: 'Audio & Music', slug: 'audio-music', icon: '🎵', count: 29 },
  { id: '9', name: 'Redesigner AI', slug: 'redesigner-ai', icon: '🪄', count: 3 },
  { id: '10', name: "API Key's", slug: 'api-keys', icon: '🔑', count: 6 },
  { id: '11', name: 'Generative Art & Image', slug: 'generative-art-image', icon: '🖼️', count: 45 },
  { id: '12', name: 'Recruitment & HR', slug: 'recruitment-hr', icon: '🤝', count: 12 },
  { id: '13', name: 'Presentation Tools', slug: 'presentation-tools', icon: '📊', count: 14 },
  { id: '14', name: 'Legal & Compliance', slug: 'legal-compliance', icon: '⚖️', count: 5 },
  { id: '15', name: 'Finance & Accounting', slug: 'finance-accounting', icon: '💰', count: 5 },
  { id: '16', name: '3D & Metaverse', slug: '3d-metaverse', icon: '🧊', count: 5 },
  { id: '17', name: 'Data Analysis & Viz', slug: 'data-analysis-viz', icon: '📊', count: 12 },
  { id: '18', name: 'Meeting & Transcription', slug: 'meeting-transcription', icon: '📝', count: 15 },
  { id: '19', name: 'Email Assistant', slug: 'email-assistant', icon: '📧', count: 14 },
  { id: '20', name: 'Website Builders', slug: 'website-builders', icon: '🌐', count: 9 },
  { id: '21', name: 'Graphic Design', slug: 'graphic-design', icon: '🎨', count: 9 },
  { id: '22', name: 'AI Detection', slug: 'ai-detection', icon: '🔍', count: 10 },
  { id: '23', name: 'Enterprise & Startups', slug: 'enterprise-startups', icon: '🚀', count: 4 },
  { id: '24', name: 'Generative Video & Agents', slug: 'generative-video-agents', icon: '📽️', count: 2 },
  { id: '25', name: 'Reasoning & Multimodal Models', slug: 'reasoning-multimodal-models', icon: '🧠', count: 4 },
  { id: '26', name: 'Business Intelligence', slug: 'business-intelligence', icon: '🏢', count: 11 },
];

const generateTools = (): AITool[] => {
  const rawList = [
    { name: 'Stability AI', cat: "API Key's", pricing: 'Paid', url: 'https://platform.stability.ai/' },
    { name: 'Picsart', cat: "API Key's", pricing: 'Paid', url: 'https://picsart.io/api/ai-image-generator' },
    { name: 'AI Horde', cat: "API Key's", pricing: 'Free', url: 'https://aihorde.net/' },
    { name: 'Stable Horde', cat: "API Key's", pricing: 'Free', url: 'https://stablehorde.net/' },
    { name: 'ClipDrop', cat: "API Key's", pricing: 'Paid', url: 'https://clipdrop.co/apis' },
    { name: 'Hugging Face', cat: "API Key's", pricing: 'Freemium', url: 'https://huggingface.co/models' },
    { name: 'Redesignr.ai', cat: 'Redesigner AI', pricing: 'Freemium', url: 'https://redesignr.ai/' },
    { name: 'MyCleverAI', cat: 'Redesigner AI', pricing: 'Freemium', url: 'https://mycleverai.com/' },
    { name: 'PageTune.ai', cat: 'Redesigner AI', pricing: 'Freemium', url: 'https://pagetune.ai/' },
    { name: 'Hiver', cat: 'Productivity', pricing: 'Freemium', url: 'https://hiverhq.com/' },
    { name: 'Zapier', cat: 'Productivity', pricing: 'Freemium', url: 'https://zapier.com/' },
    { name: 'Notion AI', cat: 'Productivity', pricing: 'Freemium', url: 'https://notion.so/' },
    { name: 'Microsoft Copilot', cat: 'Productivity', pricing: 'Paid', url: 'https://copilot.microsoft.com/' },
    { name: 'Otter.ai', cat: 'Productivity', pricing: 'Freemium', url: 'https://otter.ai/' },
    { name: 'Grammarly', cat: 'Productivity', pricing: 'Freemium', url: 'https://grammarly.com/' },
    { name: 'Motion', cat: 'Productivity', pricing: 'Paid', url: 'https://usemotion.com/' },
    { name: 'Clockwise', cat: 'Productivity', pricing: 'Freemium', url: 'https://clockwise.com/' },
    { name: 'Reclaim AI', cat: 'Productivity', pricing: 'Freemium', url: 'https://reclaim.ai/' },
    { name: 'NotebookLM', cat: 'Productivity', pricing: 'Freemium', url: 'https://notebooklm.google' },
    { name: 'ClickUp Brain', cat: 'Productivity', pricing: 'Freemium', url: 'https://clickup.com' },
    { name: 'Fireflies', cat: 'Productivity', pricing: 'Freemium', url: 'https://fireflies.ai' },
    { name: 'Fathom', cat: 'Productivity', pricing: 'Freemium', url: 'https://fathom.ai' },
    { name: 'Gamma', cat: 'Productivity', pricing: 'Freemium', url: 'https://gamma.app' },
    { name: 'Tactiq', cat: 'Productivity', pricing: 'Freemium', url: 'https://tactiq.io' },
    { name: 'NoteGPT', cat: 'Productivity', pricing: 'Freemium', url: 'https://notegpt.io' },
    { name: 'SciSpace', cat: 'Productivity', pricing: 'Freemium', url: 'https://scispace.com' },
    { name: 'Dessix.io', cat: 'Productivity', pricing: 'Freemium', url: 'https://dessix.io' },
    { name: 'ThumbnailCreator', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://thumbnailcreator.ai/' },
    { name: 'Adobe Firefly', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://firefly.adobe.com/' },
    { name: 'PXZ AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://pxz.ai/' },
    { name: 'Face Swap AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://faceswapai.online/' },
    { name: 'Artflow', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://app.artflow.ai/' },
    { name: 'Envato Labs', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://elements.envato.com/' },
    { name: 'Pixnova AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://pixnova.ai/' },
    { name: 'MimicPC', cat: 'Generative Art & Image', pricing: 'Free', url: 'https://www.mimicpc.com/' },
    { name: 'Vecteezy AI', cat: 'Generative Art & Image', pricing: 'Free', url: 'https://www.vecteezy.com/' },
    { name: 'DALL-E 3', cat: 'Generative Art & Image', pricing: 'Paid', url: 'https://openai.com/dall-e-3' },
    { name: 'Midjourney', cat: 'Generative Art & Image', pricing: 'Paid', url: 'https://midjourney.com/' },
    { name: 'Stable Diffusion', cat: 'Generative Art & Image', pricing: 'Free/Open Source', url: 'https://stability.ai/' },
    { name: 'Ideogram', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://ideogram.ai/' },
    { name: 'Leonardo AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://leonardo.ai/' },
    { name: 'Canva AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://canva.com/' },
    { name: 'Imagen 3 (Google)', cat: 'Generative Art & Image', pricing: 'Limited Access', url: 'https://deepmind.google/' },
    { name: 'Playground AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://playgroundai.com/' },
    { name: 'Napkin AI', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://napkin.ai/' },
    { name: 'Designify', cat: 'Generative Art & Image', pricing: 'Freemium', url: 'https://designify.com/' },
    { name: 'Artta AI', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://artta.ai/' },
    { name: 'Artlist', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://artlist.io/' },
    { name: 'Kling AI', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://app.klingai.com/' },
    { name: 'Higgsfield', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://higgsfield.ai/' },
    { name: 'D-ID', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://www.d-id.com/' },
    { name: 'Wondershare Filmora', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://filmora.wondershare.com/' },
    { name: 'Dreamlux AI', cat: 'Video & Motion', pricing: 'Free', url: 'https://dreamlux.ai/' },
    { name: 'KaraVideo', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://karavideo.ai/' },
    { name: 'Elai', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://elai.io/' },
    { name: 'Steve AI', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://www.steve.ai/' },
    { name: 'Synthesia', cat: 'Video & Motion', pricing: 'Paid', url: 'https://synthesia.io/' },
    { name: 'HeyEddie.ai', cat: 'Video & Motion', pricing: 'Paid', url: 'https://heyeddie.ai/' },
    { name: 'Runway', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://runwayml.com/' },
    { name: 'Pictory', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://pictory.ai/' },
    { name: 'Lumen5', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://lumen5.com/' },
    { name: 'Descript', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://descript.com/' },
    { name: 'InVideo AI', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://invideo.io/' },
    { name: 'Veed.io', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://veed.io/' },
    { name: 'CapCut', cat: 'Video & Motion', pricing: 'Free', url: 'https://capcut.com/' },
    { name: 'Veo 3', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://deepmind.google/technologies/veo/' },
    { name: 'Sora', cat: 'Video & Motion', pricing: 'Paid', url: 'https://openai.com/sora' },
    { name: 'Luma AI', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://lumalabs.ai/' },
    { name: 'HeyGen', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://heygen.com/' },
    { name: 'Fliki', cat: 'Video & Motion', pricing: 'Freemium', url: 'https://fliki.ai/' },
    { name: 'Dropmagic', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://dropmagic.ai/' },
    { name: 'WhatsApp CRM', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://whatsapp.com/' },
    { name: 'Creatify', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://creatify.ai/' },
    { name: 'Mintly', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://mintly.ai/' },
    { name: 'Jasper', cat: 'Marketing & Ads', pricing: 'Paid', url: 'https://jasper.ai/' },
    { name: 'Copy.ai', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://copy.ai/' },
    { name: 'AdCreative.ai', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://adcreative.ai/' },
    { name: 'Persado', cat: 'Marketing & Ads', pricing: 'Paid', url: 'https://persado.com/' },
    { name: 'Narrato', cat: 'Marketing & Ads', pricing: 'Freemium', url: 'https://narrato.io/' },
    { name: 'MarketMuse', cat: 'Marketing & Ads', pricing: 'Paid', url: 'https://marketmuse.com/' },
    { name: 'Munch Studio', cat: 'Social Media', pricing: 'Freemium', url: 'https://www.munchstudio.com/' },
    { name: 'Tweet Hunter', cat: 'Social Media', pricing: 'Paid', url: 'https://tweethunter.io/' },
    { name: 'Mavic AI', cat: 'Social Media', pricing: 'Freemium', url: 'https://mavic.ai/' },
    { name: 'Vista Social', cat: 'Social Media', pricing: 'Freemium', url: 'https://vistasocial.com/' },
    { name: 'Niche Traffic Kit', cat: 'Social Media', pricing: 'Freemium', url: 'https://nichetraffickit.com/' },
    { name: 'Brand24', cat: 'Social Media', pricing: 'Paid', url: 'https://brand24.com/' },
    { name: 'Buffer', cat: 'Social Media', pricing: 'Freemium', url: 'https://buffer.com/' },
    { name: 'Hootsuite', cat: 'Social Media', pricing: 'Freemium', url: 'https://hootsuite.com/' },
    { name: 'Lately AI', cat: 'Social Media', pricing: 'Paid', url: 'https://lately.ai/' },
    { name: 'Predis.ai', cat: 'Social Media', pricing: 'Freemium', url: 'https://predis.ai/' },
    { name: 'Taplio', cat: 'Social Media', pricing: 'Paid', url: 'https://taplio.com/' },
    { name: 'OpusClip', cat: 'Social Media', pricing: 'Freemium', url: 'https://www.opus.pro/' },
    { name: 'AppWizzy', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://appwizzy.com/' },
    { name: 'Emergent', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://app.emergent.sh/' },
    { name: 'YouWare', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://www.youware.com/' },
    { name: 'Replit', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://replit.com/' },
    { name: 'Tabnine', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://www.tabnine.com/' },
    { name: 'GitHub Copilot', cat: 'Coding & Dev', pricing: 'Paid', url: 'https://github.com/features/copilot' },
    { name: 'Cursor', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://cursor.sh/' },
    { name: 'Codeium', cat: 'Coding & Dev', pricing: 'Free', url: 'https://codeium.com/' },
    { name: 'Amazon CodeWhisperer', cat: 'Coding & Dev', pricing: 'Free', url: 'https://aws.amazon.com/codewhisperer/' },
    { name: 'Claude Code', cat: 'Coding & Dev', pricing: 'Paid', url: 'https://claude.ai/' },
    { name: 'Windsurf', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://codeium.com/windsurf' },
    { name: 'V0 by Vercel', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://v0.dev/' },
    { name: 'Bolt.new', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://bolt.new/' },
    { name: 'Qodo (formerly Codium)', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://qodo.ai/' },
    { name: 'Sourcegraph Cody', cat: 'Coding & Dev', pricing: 'Freemium', url: 'https://sourcegraph.com/cody' },
    { name: 'Aider', cat: 'Coding & Dev', pricing: 'Open Source', url: 'https://aider.chat/' },
    { name: 'Continue', cat: 'Coding & Dev', pricing: 'Free', url: 'https://continue.dev/' },
    { name: 'MindStudio', cat: 'Automation', pricing: 'Freemium', url: 'https://www.mindstudio.ai/' },
    { name: 'WhatsApp Chatbot (MindStudio)', cat: 'Automation', pricing: 'Freemium', url: 'https://www.mindstudio.ai/' },
    { name: 'WhatsApp Chatbot (Wadesk)', cat: 'Automation', pricing: 'Freemium', url: 'https://wadesk.io/whatsapp-chatbot' },
    { name: 'n8n', cat: 'Automation', pricing: 'Freemium', url: 'https://n8n.io/' },
    { name: 'Wadesk', cat: 'Automation', pricing: 'Freemium', url: 'https://wadesk.io/' },
    { name: 'WhatsApp Warmup Tool', cat: 'Automation', pricing: 'Paid', url: 'https://warmer.wadesk.io/' },
    { name: 'Lindy', cat: 'Automation', pricing: 'Paid', url: 'https://lindy.ai/' },
    { name: 'Hexofy', cat: 'Automation', pricing: 'Freemium', url: 'https://hexofy.com/' },
    { name: 'Make', cat: 'Automation', pricing: 'Freemium', url: 'https://make.com/' },
    { name: 'ActivePieces', cat: 'Automation', pricing: 'Free', url: 'https://activepieces.com/' },
    { name: 'Relevance AI', cat: 'Automation', pricing: 'Freemium', url: 'https://relevanceai.com/' },
    { name: 'Bardeen', cat: 'Automation', pricing: 'Freemium', url: 'https://bardeen.ai/' },
    { name: 'Suno AI', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://suno.ai/' },
    { name: 'Murf AI', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://murf.ai/' },
    { name: 'ElevenLabs', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://elevenlabs.io/' },
    { name: 'Descript', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://descript.com/' },
    { name: 'Adobe Podcast', cat: 'Audio & Music', pricing: 'Free', url: 'https://podcast.adobe.com/' },
    { name: 'AIVA', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://aiva.ai/' },
    { name: 'Soundraw', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://soundraw.io/' },
    { name: 'Lalal.ai', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://lalal.ai/' },
    { name: 'Udio', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://udio.com/' },
    { name: 'Voicemod', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://voicemod.net/' },
    { name: 'Resemble AI', cat: 'Audio & Music', pricing: 'Freemium', url: 'https://resemble.ai/' },
    { name: 'WellSaid Labs', cat: 'Audio & Music', pricing: 'Paid', url: 'https://wellsaidlabs.com/' },
    { name: 'HumanFlow', cat: 'Recruitment & HR', pricing: 'Freemium', url: 'https://humanflow.app/' },
    { name: 'HireVue', cat: 'Recruitment & HR', pricing: 'Paid', url: 'https://hirevue.com/' },
    { name: 'Paradox', cat: 'Recruitment & HR', pricing: 'Paid', url: 'https://paradox.ai/' },
    { name: 'SeekOut', cat: 'Recruitment & HR', pricing: 'Paid', url: 'https://seekout.com/' },
    { name: 'Eightfold AI', cat: 'Recruitment & HR', pricing: 'Paid', url: 'https://eightfold.ai/' },
    { name: 'Beamery', cat: 'Recruitment & HR', pricing: 'Paid', url: 'https://beamery.com/' },
    { name: 'Phenom', cat: 'Recruitment & HR', pricing: 'Paid', url: 'https://phenom.com/' },
    { name: 'Gamma', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://gamma.app/' },
    { name: 'Beautiful.ai', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://beautiful.ai/' },
    { name: 'Plus AI', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://plusai.com/' },
    { name: 'Slidesgo AI', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://slidesgo.com/ai/presentation-maker' },
    { name: 'Canva Presentations', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://canva.com/create/ai-presentations/' },
    { name: 'Presentations.AI', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://presentations.ai/' },
    { name: 'Decktopus', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://decktopus.com/' },
    { name: 'Prezi AI', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://prezi.com/' },
    { name: 'Alai', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://alai.io/' },
    { name: 'GenPPT', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://genppt.com/' },
    { name: 'MagicSlides', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://magicslides.app/' },
    { name: 'SlidesAI', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://slidesai.io/' },
    { name: 'Visme', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://visme.co/' },
    { name: 'Tome', cat: 'Presentation Tools', pricing: 'Freemium', url: 'https://tome.app/' },
    { name: 'Harvey AI', cat: 'Legal & Compliance', pricing: 'Paid', url: 'https://harvey.ai/' },
    { name: 'CoCounsel', cat: 'Legal & Compliance', pricing: 'Paid', url: 'https://casetext.com/cocounsel/' },
    { name: 'Lawgeex', cat: 'Legal & Compliance', pricing: 'Paid', url: 'https://lawgeex.com/' },
    { name: 'LawDroid', cat: 'Legal & Compliance', pricing: 'Freemium', url: 'https://lawdroid.com/' },
    { name: 'DoNotPay', cat: 'Legal & Compliance', pricing: 'Paid', url: 'https://donotpay.com/' },
    { name: 'Vic.ai', cat: 'Finance & Accounting', pricing: 'Paid', url: 'https://vic.ai/' },
    { name: 'Stampli', cat: 'Finance & Accounting', pricing: 'Paid', url: 'https://stampli.com/' },
    { name: 'Zeni', cat: 'Finance & Accounting', pricing: 'Paid', url: 'https://zeni.ai/' },
    { name: 'Booke.AI', cat: 'Finance & Accounting', pricing: 'Freemium', url: 'https://booke.ai/' },
    { name: 'Trullion', cat: 'Finance & Accounting', pricing: 'Paid', url: 'https://trullion.com/' },
    { name: 'Spline AI', cat: '3D & Metaverse', pricing: 'Freemium', url: 'https://spline.design/ai' },
    { name: 'Lumalabs', cat: '3D & Metaverse', pricing: 'Freemium', url: 'https://lumalabs.ai/' },
    { name: 'Meshy', cat: '3D & Metaverse', pricing: 'Freemium', url: 'https://meshy.ai/' },
    { name: 'Kaedim', cat: '3D & Metaverse', pricing: 'Paid', url: 'https://kaedim.com/' },
    { name: 'Alpha3D', cat: '3D & Metaverse', pricing: 'Freemium', url: 'https://alpha3d.io/' },
    { name: 'Julius AI', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://julius.ai/' },
    { name: 'ThoughtSpot', cat: 'Data Analysis & Viz', pricing: 'Paid', url: 'https://thoughtspot.com/' },
    { name: 'Zoho Analytics', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://zoho.com/analytics/' },
    { name: 'Displayr', cat: 'Data Analysis & Viz', pricing: 'Paid', url: 'https://displayr.com/' },
    { name: 'Qlik Sense', cat: 'Data Analysis & Viz', pricing: 'Paid', url: 'https://qlik.com/' },
    { name: 'Lumi AI', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://lumi-ai.com/' },
    { name: 'MonkeyLearn', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://monkeylearn.com/' },
    { name: 'Powerdrill Bloom', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://powerdrill.ai/' },
    { name: 'Data Formulator', cat: 'Data Analysis & Viz', pricing: 'Free', url: 'https://github.com/microsoft/data-formulator' },
    { name: 'Akkio', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://akkio.com/' },
    { name: 'DataRobot', cat: 'Data Analysis & Viz', pricing: 'Paid', url: 'https://datarobot.com/' },
    { name: 'H2O.ai', cat: 'Data Analysis & Viz', pricing: 'Freemium', url: 'https://h2o.ai/' },
    { name: 'Otter.ai', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://otter.ai/' },
    { name: 'Fireflies.ai', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://fireflies.ai/' },
    { name: 'Read.ai', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://read.ai/' },
    { name: 'Notta', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://notta.ai/' },
    { name: 'Tactiq', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://tactiq.io/' },
    { name: 'Jamie', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://meetjamie.ai/' },
    { name: 'MeetGeek', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://meetgeek.ai/' },
    { name: 'tl;dv', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://tldv.io/' },
    { name: 'Sembly AI', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://sembly.ai/' },
    { name: 'Granola', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://granola.so/' },
    { name: 'Fathom', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://fathom.video/' },
    { name: 'Krisp', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://krisp.ai/' },
    { name: 'Sonnet AI', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://sonnet.ai/' },
    { name: 'Superpowered', cat: 'Meeting & Transcription', pricing: 'Freemium', url: 'https://superpowered.ai/' },
    { name: 'Clarifai', cat: 'Meeting & Transcription', pricing: 'Paid', url: 'https://clarifai.com/' },
    { name: 'Superhuman', cat: 'Email Assistant', pricing: 'Paid', url: 'https://superhuman.com/' },
    { name: 'Lindy (Email)', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://lindy.ai/' },
    { name: 'MailMaestro', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://mailmaestro.com/' },
    { name: 'Spike', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://spikenow.com/' },
    { name: 'Shortwave', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://shortwave.com/' },
    { name: 'Clean Email', cat: 'Email Assistant', pricing: 'Paid', url: 'https://clean.email/' },
    { name: 'Flowrite', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://flowrite.com/' },
    { name: 'SmartWriter', cat: 'Email Assistant', pricing: 'Paid', url: 'https://smartwriter.ai/' },
    { name: 'SaneBox', cat: 'Email Assistant', pricing: 'Paid', url: 'https://sanebox.com/' },
    { name: 'ActorDo', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://actordo.com/' },
    { name: 'Hive Buzz Mail', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://hive.com/' },
    { name: 'HEY', cat: 'Email Assistant', pricing: 'Paid', url: 'https://hey.com/' },
    { name: 'Missive', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://missiveapp.com/' },
    { name: 'Spark Mail', cat: 'Email Assistant', pricing: 'Freemium', url: 'https://sparkmailapp.com/' },
    { name: 'Dorik', cat: 'Website Builders', pricing: 'Freemium', url: 'https://dorik.com/' },
    { name: 'Sitepaige', cat: 'Website Builders', pricing: 'Freemium', url: 'https://sitepaige.com/' },
    { name: 'Spectra', cat: 'Website Builders', pricing: 'Freemium', url: 'https://wpspectra.com/' },
    { name: 'Webflow', cat: 'Website Builders', pricing: 'Freemium', url: 'https://webflow.com/' },
    { name: 'Wix ADI', cat: 'Website Builders', pricing: 'Freemium', url: 'https://wix.com/' },
    { name: '10Web', cat: 'Website Builders', pricing: 'Paid', url: 'https://10web.io/' },
    { name: 'Framer', cat: 'Website Builders', pricing: 'Freemium', url: 'https://framer.com/' },
    { name: 'Durable', cat: 'Website Builders', pricing: 'Paid', url: 'https://durable.co/' },
    { name: 'Unicorn Platform', cat: 'Website Builders', pricing: 'Freemium', url: 'https://unicornplatform.com/' },
    { name: 'Adobe Express', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://www.adobe.com/express/' },
    { name: 'Logo AI', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://www.logoai.com/' },
    { name: 'Lunacy by Icons8', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://icons8.com/lunacy' },
    { name: 'Canva', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://canva.com/' },
    { name: 'Figma', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://figma.com/' },
    { name: 'Looka', cat: 'Graphic Design', pricing: 'Paid', url: 'https://looka.com/' },
    { name: 'Designify', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://designify.com/' },
    { name: 'Recraft AI', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://recraft.ai/' },
    { name: 'Kittl', cat: 'Graphic Design', pricing: 'Freemium', url: 'https://kittl.com/' },
    { name: 'isFake.ai', cat: 'AI Detection', pricing: 'Freemium', url: 'https://isfake.ai/' },
    { name: 'HIX Bypass', cat: 'AI Detection', pricing: 'Freemium', url: 'https://hixbypass.com/' },
    { name: 'Walter Writes', cat: 'AI Detection', pricing: 'Freemium', url: 'https://walterwrites.ai/' },
    { name: 'AI Detector Pro', cat: 'AI Detection', pricing: 'Freemium', url: 'https://aidetector.pro/' },
    { name: 'AI Voice Detector', cat: 'AI Detection', pricing: 'Paid', url: 'https://aivoicedetector.com/' },
    { name: 'GPTZero', cat: 'AI Detection', pricing: 'Freemium', url: 'https://gptzero.me/' },
    { name: 'Originality.ai', cat: 'AI Detection', pricing: 'Paid', url: 'https://originality.ai/' },
    { name: 'Copyleaks', cat: 'AI Detection', pricing: 'Paid', url: 'https://copyleaks.com/' },
    { name: 'Winston AI', cat: 'AI Detection', pricing: 'Paid', url: 'https://gowinston.ai/' },
    { name: 'Sapling AI', cat: 'AI Detection', pricing: 'Freemium', url: 'https://sapling.ai/' },
    { name: 'xAI Grok', cat: 'Enterprise & Startups', pricing: 'Freemium', url: 'https://x.ai' },
    { name: 'Anthropic Claude', cat: 'Enterprise & Startups', pricing: 'Paid', url: 'https://anthropic.com' },
    { name: 'Perplexity AI', cat: 'Enterprise & Startups', pricing: 'Freemium', url: 'https://perplexity.ai' },
    { name: 'Cognition AI (Devin)', cat: 'Enterprise & Startups', pricing: 'Paid', url: 'https://cognition.ai' },
    { name: 'Seedance 2.0', cat: 'Generative Video & Agents', pricing: 'Paid', url: 'https://seedance.ai' },
    { name: 'OpenClaw', cat: 'Generative Video & Agents', pricing: 'Freemium', url: 'https://open-clawai.com' },
    { name: 'Gemini 3.1 Pro', cat: 'Reasoning & Multimodal Models', pricing: 'Freemium', url: 'https://gemini.google.com' },
    { name: 'OpenAI o1/o3', cat: 'Reasoning & Multimodal Models', pricing: 'Paid', url: 'https://openai.com' },
    { name: 'Doubao 2.0', cat: 'Reasoning & Multimodal Models', pricing: 'Freemium', url: 'https://doubao.com' },
    { name: 'Sarvam 105B LLM', cat: 'Reasoning & Multimodal Models', pricing: 'Paid', url: 'https://sarvam.ai' },
    { name: 'Yorph AI', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://yorph.ai/' },
    { name: 'Liminary', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://liminary.io/' },
    { name: 'PPSPY', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://ppspy.com/' },
    { name: 'Kudra', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://gh.kudra.ai/' },
    { name: 'Upmetrics', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://upmetrics.co/' },
    { name: 'Parliant', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://www.parliant.ai/' },
    { name: 'Obviously AI', cat: 'Business Intelligence', pricing: 'Paid', url: 'https://obviously.ai/' },
    { name: 'Tableau', cat: 'Business Intelligence', pricing: 'Paid', url: 'https://tableau.com/' },
    { name: 'Power BI', cat: 'Business Intelligence', pricing: 'Freemium', url: 'https://powerbi.microsoft.com/' },
    { name: 'ThoughtSpot', cat: 'Business Intelligence', pricing: 'Paid', url: 'https://thoughtspot.com/' },
    { name: 'Qlik Sense', cat: 'Business Intelligence', pricing: 'Paid', url: 'https://qlik.com/' },
  ];

  return rawList.map((tool, index) => {
    let description = `A powerful ${tool.cat} tool that helps users leverage AI for ${tool.name.toLowerCase()} related tasks effectively.`;
    let longDescription = `${tool.name} is a comprehensive solution designed for ${tool.cat}. It integrates advanced machine learning models to streamline workflows, providing users with high-quality outputs and significant time savings.`;
    let features = ['AI-powered intelligence', 'User-friendly interface', 'Seamless integration', 'Customizable workflows'];

    if (tool.name === 'Redesignr.ai') {
      description = "Instantly redesign your website by entering its URL and describing your vision.";
      longDescription = "Redesignr.ai leverages AI to analyze your existing website and generate modern, conversion-optimized designs.";
      features = ['URL-to-Design', 'Plain English prompts', 'No-code workflow', 'Conversion optimized'];
    }

    return {
      id: `tool-${index}`,
      name: tool.name,
      slug: tool.name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, ''),
      description,
      longDescription,
      features,
      category: tool.cat,
      tags: Array.from(new Set([tool.cat.split(' ')[0], 'AI', 'API', 'Developer'])),
      pricing: tool.pricing as 'Free' | 'Freemium' | 'Paid',
      websiteUrl: tool.url,
      logoUrl: `https://picsum.photos/seed/${tool.name}/200`,
      imageUrl: `https://picsum.photos/seed/${tool.name}-ui/1200/630`,
      rating: 4.2 + (Math.random() * 0.7),
      reviewCount: Math.floor(Math.random() * 500) + 50,
      isFeatured: tool.cat === "API Key's",
      isTrending: tool.cat === "API Key's",
      createdAt: '2026-05-24',
      status: 'active',
      pros: ['Fast processing', 'High accuracy', 'Easy to use'],
      cons: ['Learning curve', 'Pricey for teams'],
      useCases: ['Content Creation', 'Data Analysis'],
      integrations: ['Slack', 'Discord', 'Zapier'],
      targetAudience: 'Professionals & Teams',
      apiAvailable: Math.random() > 0.3,
      mobileApp: Math.random() > 0.5,
      supportType: 'Priority 24/7'
    };
  });
};

export const MOCK_TOOLS: AITool[] = generateTools();

export const MOCK_SUBMISSIONS: AITool[] = [
  {
    id: 's1',
    name: 'VideoGen AI',
    slug: 'videogen-ai',
    description: 'A revolutionary tool for generating high-quality marketing videos from text descriptions.',
    features: ['Text-to-video', 'AI Voiceovers', 'Auto-subtitles'],
    category: 'Video & Motion',
    tags: ['Video', 'Marketing', 'Automation'],
    pricing: 'Freemium',
    websiteUrl: 'https://videogen.ai',
    logoUrl: 'https://picsum.photos/seed/videogen/200',
    rating: 0,
    reviewCount: 0,
    createdAt: '2026-05-24',
    status: 'pending'
  }
];

// Added missing MOCK_AUTHORS to fix AdminBlog import error
export const MOCK_AUTHORS = {
  alex: {
    name: 'Alex Rivera',
    role: 'Lead AI Researcher',
    bio: 'Alex has been covering the AI beat since 2018, specializing in large language models and productivity automation.',
    imageUrl: 'https://picsum.photos/seed/alex/200'
  }
};

export const MOCK_POSTS: BlogPost[] = [
  {
    id: 'p1',
    title: 'The Rise of Generative AI in 2026',
    slug: 'rise-of-generative-ai-2026',
    excerpt: 'Exploring how generative models are reshaping industries from software development to creative arts.',
    content: '<p>Generative AI has come a long way since the early days of 2023. In 2026, we are seeing a massive shift in how businesses operate...</p><h2>The Impact on Creative Industries</h2><p>Artists and designers are now using AI as a collaborative partner rather than just a tool...</p>',
    author: MOCK_AUTHORS.alex,
    date: 'May 15, 2026',
    imageUrl: 'https://picsum.photos/seed/ai-rise/1200/630',
    category: 'Industry Updates',
    tags: ['AI', 'Future', 'Tech'],
    metaTitle: 'The Rise of Generative AI in 2026 | AIZONET',
    metaDescription: 'Exploring how generative models are reshaping industries in 2026.'
  },
  {
    id: 'p2',
    title: 'Top 10 Productivity AI Tools for Developers',
    slug: 'top-10-productivity-ai-tools-developers',
    excerpt: 'A curated list of the best AI tools to help developers write better code faster.',
    content: '<p>As a developer, staying productive is key. Here are the top 10 AI tools that are making waves in the dev community...</p><h2>1. Cursor</h2><p>Cursor remains the king of AI-powered IDEs...</p>',
    author: MOCK_AUTHORS.alex,
    date: 'May 10, 2026',
    imageUrl: 'https://picsum.photos/seed/dev-tools/1200/630',
    category: 'AI Tools Reviews',
    tags: ['Developers', 'Productivity', 'Coding'],
    metaTitle: 'Top 10 Productivity AI Tools for Developers | AIZONET',
    metaDescription: 'Best AI tools for developers in 2026.'
  }
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  seo: {
    siteUrl: 'https://aizonet.in',
    googleAnalyticsId: 'G-AIZONET2026',
    googleSearchConsoleId: 'sc-verification-placeholder-2026',
    bingVerification: 'bing-site-verification=aizonet_verified',
    yandexVerification: 'yandex-verification=aizonet_verified',
    baiduVerification: '',
    pinterestVerification: '',
    facebookDomainVerification: '',
    robotsTxt: 'User-agent: *\nAllow: /\nSitemap: https://aizonet.in/sitemap.xml',
    sitemapUrl: 'https://aizonet.in/sitemap.xml'
  },
  ads: {
    adSenseClientId: 'ca-pub-aizonet',
    placements: {
      header: { id: 'h1', name: 'Header Ad', isEnabled: true, code: '<div class="h-20 w-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-xs text-slate-400">Leaderboard Ad (728x90)</div>' },
      footer: { id: 'f1', name: 'Footer Ad', isEnabled: true, code: '<div class="h-24 w-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-xs text-slate-400">Footer Banner Ad</div>' },
      blogContent: { id: 'b1', name: 'Blog Post Ad', isEnabled: true, code: '<div class="h-64 w-full bg-slate-50 dark:bg-slate-900 border border-dashed rounded-xl flex items-center justify-center text-xs text-slate-400 my-8">Article Contextual Ad</div>' },
      toolDirectory: { id: 't1', name: 'Directory Ad', isEnabled: true, code: '<div class="h-full min-h-[150px] w-full bg-indigo-50 dark:bg-indigo-950/20 border-2 border-dashed border-indigo-200 dark:border-indigo-900 rounded-2xl flex items-center justify-center text-center p-4 text-xs text-indigo-400 font-bold">SPONSORED SPACE</div>' },
    }
  }
};
